### ISSUE TITLE
Consider adding LGTM.com runner to the CI.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1585]
## Description

LGTM.com: Continuous security analysis

A code analysis platform for finding zero-days and preventing critical vulnerabilities

**Comment by ronaldtse** [comment]
@ni4 I've added LGTM, and we need to configure its build:
<img width="1130" alt="Screenshot 2021-10-13 at 5 35 09 PM" src="https://user-images.githubusercontent.com/11865/137107720-848130cc-0b1d-45c8-b11d-1c3b4fa87e3e.png">

Relevant link:
https://lgtm.com/help/lgtm/customizing-code-extraction

Sample configuration file:
```yaml
extraction:
  cpp:
     prepare:
        packages: 
          - libboost-all-dev
          - bison
     configure:
        command:
        - ./bootstrap
        - ./configure --with-modules="" --without-lua
     index:
        build_command:
        - ./project-builder.sh
```

Badge: 
```md
[![Total alerts](https://img.shields.io/lgtm/alerts/g/rnpgp/rnp.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/rnpgp/rnp/alerts/)
```
